begin;
create extension if not exists pgtap with schema extensions;
select plan(16);
select has_table('public','commercial_routines','commercial_routines exists');
select ok((select relrowsecurity from pg_class where oid='public.commercial_routines'::regclass),'commercial_routines enables RLS');
select ok(not has_table_privilege('anon','public.commercial_routines','select,insert,update,delete'),'anon cannot access commercial_routines directly');
select ok(not has_table_privilege('authenticated','public.commercial_routines','select,insert,update,delete'),'authenticated cannot access commercial_routines directly');
select has_table('public','portfolio_analyses','portfolio_analyses exists');
select ok((select relrowsecurity from pg_class where oid='public.portfolio_analyses'::regclass),'portfolio_analyses enables RLS');
select ok(not has_table_privilege('anon','public.portfolio_analyses','select,insert,update,delete'),'anon cannot access portfolio_analyses directly');
select ok(not has_table_privilege('authenticated','public.portfolio_analyses','select,insert,update,delete'),'authenticated cannot access portfolio_analyses directly');
select has_table('public','commercial_proposals','commercial_proposals exists');
select ok((select relrowsecurity from pg_class where oid='public.commercial_proposals'::regclass),'commercial_proposals enables RLS');
select ok(not has_table_privilege('anon','public.commercial_proposals','select,insert,update,delete'),'anon cannot access commercial_proposals directly');
select ok(not has_table_privilege('authenticated','public.commercial_proposals','select,insert,update,delete'),'authenticated cannot access commercial_proposals directly');
select has_table('public','recommendation_context_guards','recommendation_context_guards exists');
select ok((select relrowsecurity from pg_class where oid='public.recommendation_context_guards'::regclass),'recommendation_context_guards enables RLS');
select ok(not has_table_privilege('anon','public.recommendation_context_guards','select,insert,update,delete'),'anon cannot access recommendation_context_guards directly');
select ok(not has_table_privilege('authenticated','public.recommendation_context_guards','select,insert,update,delete'),'authenticated cannot access recommendation_context_guards directly');
select * from finish();
rollback;
