begin;
create extension if not exists pgtap with schema extensions;
select plan(37);
select ok(exists(select 1 from pg_extension where extname='vector'),'pgvector available');
select has_table('public','knowledge_settings','knowledge_settings exists');
select ok((select relrowsecurity from pg_class where oid='public.knowledge_settings'::regclass),'knowledge_settings RLS');
select ok(not has_table_privilege('anon','public.knowledge_settings','select,insert,update,delete'),'anon knowledge_settings denied');
select ok(not has_table_privilege('authenticated','public.knowledge_settings','select,insert,update,delete'),'browser knowledge_settings denied');
select has_table('public','knowledge_documents','knowledge_documents exists');
select ok((select relrowsecurity from pg_class where oid='public.knowledge_documents'::regclass),'knowledge_documents RLS');
select ok(not has_table_privilege('anon','public.knowledge_documents','select,insert,update,delete'),'anon knowledge_documents denied');
select ok(not has_table_privilege('authenticated','public.knowledge_documents','select,insert,update,delete'),'browser knowledge_documents denied');
select has_table('public','knowledge_versions','knowledge_versions exists');
select ok((select relrowsecurity from pg_class where oid='public.knowledge_versions'::regclass),'knowledge_versions RLS');
select ok(not has_table_privilege('anon','public.knowledge_versions','select,insert,update,delete'),'anon knowledge_versions denied');
select ok(not has_table_privilege('authenticated','public.knowledge_versions','select,insert,update,delete'),'browser knowledge_versions denied');
select has_table('public','knowledge_chunks','knowledge_chunks exists');
select ok((select relrowsecurity from pg_class where oid='public.knowledge_chunks'::regclass),'knowledge_chunks RLS');
select ok(not has_table_privilege('anon','public.knowledge_chunks','select,insert,update,delete'),'anon knowledge_chunks denied');
select ok(not has_table_privilege('authenticated','public.knowledge_chunks','select,insert,update,delete'),'browser knowledge_chunks denied');
select has_table('public','knowledge_audit','knowledge_audit exists');
select ok((select relrowsecurity from pg_class where oid='public.knowledge_audit'::regclass),'knowledge_audit RLS');
select ok(not has_table_privilege('anon','public.knowledge_audit','select,insert,update,delete'),'anon knowledge_audit denied');
select ok(not has_table_privilege('authenticated','public.knowledge_audit','select,insert,update,delete'),'browser knowledge_audit denied');
select has_table('public','knowledge_reads','knowledge_reads exists');
select ok((select relrowsecurity from pg_class where oid='public.knowledge_reads'::regclass),'knowledge_reads RLS');
select ok(not has_table_privilege('anon','public.knowledge_reads','select,insert,update,delete'),'anon knowledge_reads denied');
select ok(not has_table_privilege('authenticated','public.knowledge_reads','select,insert,update,delete'),'browser knowledge_reads denied');
select has_table('public','knowledge_embedding_budget','knowledge_embedding_budget exists');
select ok((select relrowsecurity from pg_class where oid='public.knowledge_embedding_budget'::regclass),'knowledge_embedding_budget RLS');
select ok(not has_table_privilege('anon','public.knowledge_embedding_budget','select,insert,update,delete'),'anon knowledge_embedding_budget denied');
select ok(not has_table_privilege('authenticated','public.knowledge_embedding_budget','select,insert,update,delete'),'browser knowledge_embedding_budget denied');
select has_table('public','outcome_evaluations','outcome_evaluations exists');
select ok((select relrowsecurity from pg_class where oid='public.outcome_evaluations'::regclass),'outcome_evaluations RLS');
select ok(not has_table_privilege('anon','public.outcome_evaluations','select,insert,update,delete'),'anon outcome_evaluations denied');
select ok(not has_table_privilege('authenticated','public.outcome_evaluations','select,insert,update,delete'),'browser outcome_evaluations denied');
select has_table('public','outcome_feedback','outcome_feedback exists');
select ok((select relrowsecurity from pg_class where oid='public.outcome_feedback'::regclass),'outcome_feedback RLS');
select ok(not has_table_privilege('anon','public.outcome_feedback','select,insert,update,delete'),'anon outcome_feedback denied');
select ok(not has_table_privilege('authenticated','public.outcome_feedback','select,insert,update,delete'),'browser outcome_feedback denied');
select * from finish();
rollback;
