// Generated by scripts/generate-agent-contract.py from FastAPI OpenAPI.
export type AgentMetrics = {
  agent_name: string;
  agent_version: string;
  generation_mode: "agno_openai" | "deterministic_fallback";
  model_id: string | null;
  runs: number;
  running: number;
  succeeded: number;
  degraded: number;
  failed: number;
  latency_samples: number;
  latency_p95_ms: number | null;
  last_run_at: string;
  cost_usd: number | null;
  cost_status: "not_instrumented" | "partial" | "calculated";
  usage_samples?: number;
  cost_samples?: number;
  not_called?: number;
  input_tokens?: number | null;
  output_tokens?: number | null;
  autonomy: "proposal_only" | "read_only";
};

export type AgentWindow = {
  since: string;
  until: string;
  days: number;
};

export type AgentSummary = {
  items: Array<AgentMetrics>;
  window: AgentWindow;
  source: string;
  freshness_at: string;
  latency_definition: "run_wall_time_ms";
  limitations: Array<string>;
};

export type GraphNode = {
  id: string;
  kind: string;
  label: string;
  external_ref: string;
};

export type GraphEdge = {
  src_id: string;
  dst_id: string;
  kind: string;
  evidence_event_id: string;
  valid_from: string;
  depth: number;
  event_type: string;
  source: string;
  occurred_at: string;
  derivation_version: string;
};

export type OpportunityGraph = {
  root_id: string;
  nodes: Array<GraphNode>;
  edges: Array<GraphEdge>;
  depth: number;
  edge_limit: number;
  truncated: boolean;
  source: string;
  freshness_at: string;
  period: string;
  derivation_version: string;
};

export type QuotaCommand = {
  reason: string;
  expected_version: number;
  seats_limit: number;
  ai_daily_budget_brl: number | string;
  ai_monthly_budget_brl: number | string;
  usd_brl_rate: number | string;
  rate_source: string;
};

export type QuotaRecord = {
  seats_limit: number;
  ai_daily_budget_brl: string;
  ai_monthly_budget_brl: string;
  usd_brl_rate: string;
  rate_source: string;
  updated_at: string;
};

export type InviteCommand = {
  email: string;
  role: "admin" | "manager" | "seller" | "auditor";
  reason: string;
};

export type ActivateCommand = {
  user_id: string;
  expected_version: number;
  reason: string;
};

export type MembershipCommand = {
  expected_version: number;
  active: boolean;
  reason: string;
};

export type LicensePage = {
  seats_limit: number;
  used: number;
  invitations: Array<InvitationRecord>;
  memberships: Array<MembershipRecord>;
  next_invitation: string | null;
  next_member: string | null;
};

export type InvitationRecord = {
  id: string;
  email: string;
  role: string;
  status: string;
  version: number;
};

export type MembershipRecord = {
  user_id: string;
  email?: string | null;
  role: string;
  active: boolean;
  version: number;
};

export type LeadInput = {
  name: string;
  email?: string | null;
  phone?: string | null;
  idempotency_key: string;
};

export type LeadResolve = {
  action: "create" | "merge" | "discard" | "undo";
  expected_version: number;
  target_subject_id?: string | null;
  reason: string;
};

export type LeadRecord = {
  id: string;
  name: string;
  email: string | null;
  phone: string | null;
  status: string;
  version: number;
  owner_id: string;
  target_subject_id: string | null;
  external_id: string | null;
  correlation_id: string;
  created_at: string;
};

export type LeadPage = {
  items: Array<LeadRecord>;
  next_cursor: string | null;
  can_create: boolean;
};

export type LeadCandidate = {
  id: string;
  display_name: string;
  score: number;
  reasons: Array<string>;
};

export type ImpactWindow = {
  since: string;
  until: string;
  days: number;
};

export type ImpactCounts = {
  at_risk: number;
  worked: number;
};

export type ImpactAmount = {
  currency: string | null;
  observations: number;
  synthetic_observations: number;
  sales_observed: number;
  recovered: number;
  sale_value: string | null;
  ares_influenced_value: string | null;
  incremental_value: string | null;
  freshness_at: string | null;
};

export type ImpactCost = {
  runs: number;
  measured_runs: number;
  cost_usd: string | null;
};

export type ImpactSummary = {
  window: ImpactWindow;
  counts: ImpactCounts;
  amounts: Array<ImpactAmount>;
  ai_cost: ImpactCost;
  source: string;
  computed_at: string;
  definitions: Array<string>;
};

export type ImpactIntervention = {
  intervention_id: string;
  opportunity_id: string;
  correlation_id: string;
  status: string;
  state_before_ref: string;
  state_after_ref: string | null;
  created_at: string;
  closed_at: string | null;
  result_type: string | null;
  sale_value: string | null;
  ares_influenced_value: string | null;
  incremental_value: string | null;
  currency: string | null;
  attribution_level: string | null;
  attribution_method: string | null;
  observed_at: string | null;
};

export type ImpactPage = {
  items: Array<ImpactIntervention>;
  next_cursor: string | null;
};

export type ChatCitation = {
  event_id: string;
  event_type?: string | null;
  occurred_at?: string | null;
  source?: string | null;
  source_ref?: string | null;
};

export type ChatContext = {
  context_ref: string;
  content: string;
  content_hash: string;
  tokens_upper_bound: number;
  token_limit: number;
  count_method: string;
  citations: Array<ChatCitation>;
  truncated: boolean;
  captured_at: string;
  source: string;
  instruction_tokens_upper_bound?: number | null;
  question_tokens_upper_bound?: number | null;
};

export type ChatTool = {
  name: string;
  status: string;
};

export type ChatExchange = {
  id: string;
  user_text: string;
  assistant_text: string;
  status: string;
  context_json: ChatContext;
  tool_calls_json: Array<ChatTool>;
  created_at: string;
};

export type ChatHistory = {
  items: Array<ChatExchange>;
  context: ChatContext;
  model_available: boolean;
};

export type ChatCommand = {
  text: string;
  scope_ref: string;
};

export type TenantRecord = {
  id: string;
  name: string;
  slug: string;
  status: string;
  version: number;
  created_at: string;
  updated_at: string;
};

export type TenantPage = {
  items: Array<TenantRecord>;
  next_cursor: string | null;
};

export type EntitlementRecord = {
  module: string;
  status: string;
  granted_at: string;
  expires_at: string | null;
};

export type BillingRecord = {
  state: string;
  due_since: string | null;
  grace_until: string | null;
  reason: string;
  changed_at: string;
};

export type BillingCommand = {
  reason: string;
  expected_version: number;
  state: "active" | "past_due" | "degraded";
  due_since?: string | null;
  grace_until?: string | null;
};

export type TenantConfiguration = {
  tenant: TenantRecord;
  entitlements: Array<EntitlementRecord>;
  billing?: BillingRecord | null;
  quota?: QuotaRecord | null;
};

export type CreateTenant = {
  reason: string;
  name: string;
  slug: string;
};

export type SetEntitlement = {
  reason: string;
  expected_version: number;
  module: "stellar" | "ares_connect" | "ares_crm";
  status: "active" | "suspended" | "revoked";
  expires_at?: string | null;
};

export type CommandCenterWindow = {
  since: string;
  until: string;
  days: number;
};

export type CommandCenterScope = {
  mode: "tenant" | "own";
  role: string;
  owner_user_id: string | null;
};

export type CommandCenterCapabilities = {
  approve: boolean;
  assign: boolean;
  fix_connection: boolean;
};

export type ValueAtRisk = {
  currency: string | null;
  total: string | null;
  count: number;
  missing: number;
};

export type QueueItem = {
  opportunity_id: string;
  title: string | null;
  state: string;
  priority: number;
  score: string | null;
  sla_at: string | null;
  owner_user_id: string | null;
  primary_signal_type: string | null;
  signal_count: number;
  deal_value: string | null;
  currency: string | null;
  pending_approval_id: string | null;
};

export type ApprovalItem = {
  approval_id: string;
  opportunity_id: string;
  title: string | null;
  urgency: string | null;
  required_role: string;
  expires_at: string | null;
  created_at: string;
};

export type ApprovalsBlock = {
  pending: number;
  expiring_within_6h: number;
  items_limit: number;
  items: Array<ApprovalItem>;
};

export type FailedActionItem = {
  execution_id: string;
  opportunity_id: string;
  title: string | null;
  action_kind: string | null;
  attempts: number;
  finished_at: string | null;
  correlation_id: string;
};

export type FailedActionsBlock = {
  count: number;
  items_limit: number;
  items: Array<FailedActionItem>;
};

export type ConnectionItem = {
  connection_id: string;
  provider: string;
  status: string;
  last_sync_at: string | null;
};

export type ConnectionsBlock = {
  total: number;
  degraded: number;
  revoked: number;
  items: Array<ConnectionItem>;
};

export type NowBlock = {
  open_at_risk: number;
  critical: number;
  sla_overdue: number;
  sla_next_6h: number;
  sla_missing: number;
  without_owner: number;
  awaiting_decision: number;
  value_at_risk: Array<ValueAtRisk>;
  queue: Array<QueueItem>;
  queue_limit: number;
  approvals: ApprovalsBlock;
  failed_actions: FailedActionsBlock;
  connections: ConnectionsBlock;
  freshness_at: string | null;
};

export type CommandCenterImpact = {
  window: ImpactWindow;
  counts: ImpactCounts;
  amounts: Array<ImpactAmount>;
  ai_cost: ImpactCost | null;
  source: string;
  computed_at: string;
  definitions: Array<string>;
};

export type TrendSeries = {
  key: string;
  label: string;
  values: Array<number>;
};

export type TrendsBlock = {
  days: Array<string>;
  series: Array<TrendSeries>;
  freshness_at: string | null;
};

export type FunnelStage = {
  state: string;
  label: string;
  reached: number;
};

export type FunnelBlock = {
  cohort: number;
  stages: Array<FunnelStage>;
};

export type SignalType = {
  signal_type: string;
  severity: number;
  total: number;
};

export type SignalCell = {
  day: string;
  signal_type: string;
  count: number;
};

export type SignalsBlock = {
  total: number;
  without_opportunity: number;
  days: Array<string>;
  types: Array<SignalType>;
  cells: Array<SignalCell>;
  freshness_at: string | null;
};

export type HeatmapCell = {
  weekday: number;
  band: number;
  count: number;
};

export type HeatmapBlock = {
  total: number;
  timezone: string;
  cells: Array<HeatmapCell>;
};

export type ActivityItem = {
  kind: "state" | "decision" | "action" | "outcome";
  occurred_at: string;
  actor_type: string | null;
  opportunity_id: string | null;
  title: string | null;
  label: string | null;
  detail: string | null;
  attribution_level: string | null;
  correlation_id: string | null;
};

export type ActivityBlock = {
  limit: number;
  truncated: boolean;
  items: Array<ActivityItem>;
};

export type CoverageBlock = {
  opportunities: number;
  opportunities_with_owner: number;
  opportunities_with_sla: number;
  deals_with_value: number;
  signals_with_opportunity: number;
  synthetic_outcomes: number;
  ai_runs: number | null;
  ai_measured_runs: number | null;
};

export type MetricDefinition = {
  key: string;
  label: string;
  formula: string;
  tables: Array<string>;
  period: string;
  attribution_level: string | null;
  attribution: string;
};

export type CommandCenterSummary = {
  window: CommandCenterWindow;
  scope: CommandCenterScope;
  capabilities: CommandCenterCapabilities;
  now: NowBlock;
  impact: CommandCenterImpact;
  trends: TrendsBlock;
  funnel: FunnelBlock;
  signals: SignalsBlock;
  heatmap: HeatmapBlock;
  activity: ActivityBlock;
  coverage: CoverageBlock;
  definitions: Array<MetricDefinition>;
  source: string;
  freshness_at: string | null;
  computed_at: string;
};
