"""Generate the agent read contract from FastAPI OpenAPI without a new dependency."""

import json
from pathlib import Path
from typing import Any

from ares.api.app import app


def ts(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return str(schema["$ref"]).rsplit("/", 1)[-1]
    if "anyOf" in schema:
        return " | ".join(ts(item) for item in schema["anyOf"])
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(item) for item in schema["enum"])
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{ts(schema['items'])}>"
    if kind == "object":
        required = schema.get("required", [])
        fields = [
            f"  {name}{'' if name in required else '?'}: {ts(value)};"
            for name, value in schema.get("properties", {}).items()
        ]
        return "{\n" + "\n".join(fields) + "\n}"
    mapping = {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }
    if kind not in mapping:
        raise ValueError(f"Unsupported OpenAPI type: {kind}")
    return mapping[kind]


schemas = app.openapi()["components"]["schemas"]
names = ("AgentMetrics", "AgentWindow", "AgentSummary", "GraphNode", "GraphEdge", "OpportunityGraph",
         "QuotaCommand", "QuotaRecord", "InviteCommand", "ActivateCommand", "MembershipCommand", "LicensePage", "InvitationRecord", "MembershipRecord",
         "LeadInput", "LeadResolve", "LeadRecord", "LeadPage", "LeadCandidate",
         "ImpactWindow", "ImpactCounts", "ImpactAmount", "ImpactCost", "ImpactSummary", "ImpactIntervention", "ImpactPage",
         "ChatCitation", "ChatContext", "ChatTool", "ChatExchange", "ChatHistory", "ChatCommand",
         "TenantRecord", "TenantPage", "EntitlementRecord", "BillingRecord", "BillingCommand", "TenantConfiguration", "CreateTenant", "SetEntitlement",
         "CommandCenterWindow", "CommandCenterScope", "CommandCenterCapabilities", "ValueAtRisk", "QueueItem", "ApprovalItem", "ApprovalsBlock",
         "FailedActionItem", "FailedActionsBlock", "ConnectionItem", "ConnectionsBlock", "NowBlock", "CommandCenterImpact", "TrendSeries", "TrendsBlock",
         "FunnelStage", "FunnelBlock", "SignalType", "SignalCell", "SignalsBlock", "HeatmapCell", "HeatmapBlock", "ActivityItem", "ActivityBlock",
         "CoverageBlock", "MetricDefinition", "CommandCenterSummary")
content = "// Generated by scripts/generate-agent-contract.py from FastAPI OpenAPI.\n"
content += "\n".join(f"export type {name} = {ts(schemas[name])};\n" for name in names)
target = (
    Path(__file__).resolve().parents[1] / "apps/web/src/features/agents/contract.ts"
)
target.parent.mkdir(parents=True, exist_ok=True)
target.write_text(content, encoding="utf-8")
